deps: set up testing suite
distributeaid/next-website-v2 pull request #118
Opened 2024-08-21 18:38 UTC by CatherineKiiru

## What Changed
Setup React Testing Library & Vitest
Closes #103

2024-08-29 03:43 UTC, jtfairbank requested changes
**praise:** tests work for me @CatherineKiiru!

**suggestion (blocking):** i think it'd be helpful to include a real test in this PR so we have a relevant example for others to follow.  the hello world is a good proof of concept, but could we replace it with something simple that tests the functionality of a component, or that a page loads, or something?

**chore (blocking):** could you rebase with the latest version of `saga`?  at some point i updated all the fonts to use our new ones, and there are a few files here that have since been deleted

2024-09-09 17:07 UTC, CatherineKiiru commented
@jtfairbank fixed merge conflicts and added a more detailed test example.

2024-11-09 14:14 UTC, jtfairbank commented
@IAmJSD looks great!

**Question:** How come we're using `on: pull` instead of `on: pull_request`?

2024-11-09 14:38 UTC, IAmJSD commented
@jtfairbank on pull_request seems to have some problems with updating for future pushes (see the other workflows problems running until I changed it above for an example)

2024-11-09 14:51 UTC, IAmJSD commented
will handle merge conflict now

2024-11-09 16:17 UTC, jtfairbank approved these changes

2024-11-09 16:18 UTC, merged