feat: navbar component
distributeaid/next-website-v2 pull request #120
Opened 2024-08-22 13:07 UTC by CatherineKiiru

## What changed

- Reworked the Navbar component to  use Radix Primitives
- Cleaned up the UI
- Fixes #88

2024-08-29 03:35 UTC, jtfairbank approved these changes
**praise:** @CatherineKiiru great job using Radix primitives!  Exciting to have an example of that in the code.

**suggestion(non-blocking):** It seems like there are a lot of tailwind classes that we could replace with Radix components, such as [Flex](https://www.radix-ui.com/themes/docs/components/flex), [Box](https://www.radix-ui.com/themes/docs/components/box) (padding, etc), and [Text](https://www.radix-ui.com/themes/docs/components/text).  Could you try to use these when relevant, and refactor out the tailwind classes?

* Note: You can use the [asChild](https://www.radix-ui.com/primitives/docs/guides/composition) radix property to pass classes down as well!!  For example, you could wrap the logo with a `<Box>` and set the width, height, and margin properties.  Using `asChild` would pass those to the image itself, instead of wrapping it in a div.

**praise:** mobile responsive looks good!  there's an issue on the home page but that doesn't seem to be related to the menu

Feel free to merge if you want to now!  Or you can try out the approach in my suggestion.

2024-10-30 18:23 UTC, littilemike11 requested changes

2024-10-30 18:23 UTC, littilemike11 commented on src/components/nav/navBar.tsx
> +                "p-3 px-12 cursor-pointer capitalize font-medium hover:scale-105 hover:bg-dark-blue hover:rounded-lg duration-200",
**issue(ux, blocking)** : The button click on nav menu only registers when you click on the actual word, not including the background of the button.
**suggestion**: move classname from li to <Link> (84)

2024-10-30 18:47 UTC, littilemike11 approved these changes

2024-10-31 17:39 UTC, merged